services:

  realsense:
    command: /bin/bash
    build:
      context: .
      dockerfile: focal-from-patch.Dockerfile
      #runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - $RS_WS/shared:/home/shared
      - $ROL_WS/src:/home/overlay_ws/src
    devices:      
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video4:/dev/video4
      - /dev/video5:/dev/video5
               
  realsense-build:
    command: /bin/bash
    build:
      context: .
      dockerfile: focal-patch.Dockerfile    
    #image: intelrealsense-realsense-patch:focal-patch
    #image: intelrealsense-realsense-build:focal-patch-ros
    # runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - $RS_WS/shared:/home/shared
      - $ROL_WS/src:/home/overlay_ws/src  
        #    devices:      
        #      - /dev/video0:/dev/video0
        #      - /dev/video1:/dev/video1
        #      - /dev/video2:/dev/video2
        #      - /dev/video3:/dev/video3
        #      - /dev/video4:/dev/video4
        #      - /dev/video5:/dev/video5
