services:
#  realsense-viewer:
#    command: realsense-viewer
#    build: .
#    runtime: nvidia
#    environment:
#      DISPLAY: $DISPLAY
#    volumes:
#      - /tmp/.X11-unix:/tmp/.X11-unix
#      - ~/.Xauthority:/root/.Xauthority
#      - $RS_WS_PATH/src:/home/realsense_ws/src
#    devices:
#      - /dev/video0:/dev/video0
#      - /dev/video1:/dev/video1
#      - /dev/video2:/dev/video2
#      - /dev/video3:/dev/video3
#      - /dev/video4:/dev/video4
#      - /dev/video5:/dev/video5
  realsense-build:
    command: /bin/bash
    build:
      context: .
      dockerfile: focal.Dockerfile
    runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - $RS_WS_PATH/src:/home/realsense_ws/src

  realsense:
    command: /bin/bash
    image: intelrealsense-realsense-build:focal-515-ros
    runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - $RS_WS_PATH/src:/home/realsense_ws/src
    devices:      
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video4:/dev/video4
      - /dev/video5:/dev/video5

