services:
#  realsense-build:
#    command: /bin/bash
#    build:
#      context: .
#      dockerfile: focal.Dockerfile
# #    runtime: nvidia
#    environment:
#      DISPLAY: $DISPLAY
#    volumes:
#      - /tmp/.X11-unix:/tmp/.X11-unix
#      - ~/.Xauthority:/root/.Xauthority
#      - $RS_WS/shared:/home/realsense_ws/shared  
#      - $RS_WS/src:/home/realsense_ws/src
#      #- $ROS_WS/src:/home/catkin_ws/src

  realsense:
    command: /bin/bash
    build:
      context: .
      dockerfile: focal.Dockerfile
 #  runtime: nvidia
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - $RS_WS/shared:/home/shared
      - $ROL_WS/src:/home/overlay_ws/src
    devices:      
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video4:/dev/video4
      - /dev/video5:/dev/video5
      - /dev/video4:/dev/video6
      - /dev/video5:/dev/video7

#  realsense-patch:
#    command: /bin/bash
#    image: intelrealsense-realsense-build:focal-patch-ros
# #  runtime: nvidia
#    environment:
#      DISPLAY: $DISPLAY
#    volumes:
#      - /tmp/.X11-unix:/tmp/.X11-unix
#      - ~/.Xauthority:/root/.Xauthority
#      - $RS_WS/shared:/home/realsense_ws/shared
#      - $RS_WS/src:/home/realsense_ws/src
#      - $ROS_WS/src:/home/catkin_ws/src  
#    devices:      
#      - /dev/video0:/dev/video0
#      - /dev/video1:/dev/video1
#      - /dev/video2:/dev/video2
#      - /dev/video3:/dev/video3
#      - /dev/video4:/dev/video4
#      - /dev/video5:/dev/video5
#
